---
data_dir:
  models:
    huggingface: "./models/huggingface"
    lora: "./models/lora"

preloaded_models:
  base:
    - id: "runwayml/stable-diffusion-v1-5"
    - id: "emilianJR/chilloutmix_NiPrunedFp32Fix"
    - id: "stabilityai/stable-diffusion-xl-base-1.0"
      variant: "fp16"
    - id: "stabilityai/stable-diffusion-xl-refiner-1.0"
      variant: "fp16"
    - id: "a1079602570/animefull-final-pruned"
  controlnet:
    - id: "lllyasviel/sd-controlnet-canny"
    - id: "diffusers/controlnet-canny-sdxl-1.0"
  vae:
